version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: micro
      POSTGRES_PASSWORD: micro
      POSTGRES_DB: micro
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
